# Site settings
name: lamccloskey
email: lamccloskey@gmail.com
url: http://loganmccloskey.com
description: "my litte website"
author: "Logan McCloskey"
title: "do the thing and become it"
permalink: pretty

# social
github:
  username: lamccloskey

linkedin:
  username: lamccloskey

twitter:
  username: lamccloskey

# comments
disqus: true