# Site settings
name: lamccloskey
email: lamccloskey@gmail.com
url: http://loganmccloskey.com
description: "My professional website"
author: "Logan McCloskey"
title: "Logan McCloskey"
permalink: pretty

# social
github:
  username: lamccloskey

linkedin:
  username: lamccloskey

twitter:
  username: lamccloskey

# comments
disqus: false

sass:
  style: compressed