# Site settings
name: lamccloskey
email: lamccloskey@gmail.com
url: http://loganmccloskey.com
description: "Just a little blog"
author: "Logan McCloskey"
title: "Yet Another Blog"
permalink: pretty

# social
github:
  username: lamccloskey

linkedin:
  username: lamccloskey

twitter:
  username: lamccloskey

  # Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: lamccloskey